<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2cxIEJG\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2cxIEJG/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2cxIEJG.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2cxIEJG\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container2cxIEJG\srcDevDebugProjectContainer(array(
    'container.build_hash' => '2cxIEJG',
    'container.build_id' => 'fc40b3f0',
    'container.build_time' => 1678395968,
), __DIR__.\DIRECTORY_SEPARATOR.'Container2cxIEJG');
