<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1xpPoGX\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1xpPoGX/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container1xpPoGX.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container1xpPoGX\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container1xpPoGX\srcDevDebugProjectContainer(array(
    'container.build_hash' => '1xpPoGX',
    'container.build_id' => '8ecb60f4',
    'container.build_time' => 1678465840,
), __DIR__.\DIRECTORY_SEPARATOR.'Container1xpPoGX');
